### ISSUE TITLE
Keep track of last page viewed

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/database-viewer#14]
As an on and off editor, it would help to remember the last page I worked on proofing. If there is github integration and you can check the ID of the last issue I opened, it would at least be good enough to give an idea to me of where to work forward from.

**Comment by Harjot1Singh** [comment]
Would the last page viewed in the editor help?

**Comment by Harjot1Singh** [comment]
What if we had a button/link on the sources page that said `You were last on page x of source y`?

We can store this in localstorage for now, since I'll assume that most of the time, people use the same browser and machine
