### ISSUE TITLE
Linkify each selectable line

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/database-viewer#24]
Add link to issue template so the correction can be viewed in context of db-viewer.

**Comment by Harjot1Singh** [comment]
Is this done? In your commits, use the keywords Closes, Close, Fixes, Fix before each issue number to automatically have them close on commit.

**Comment by bhajneet** [comment]
Not done at all

**Comment by saihaj** [comment]
Is it not done? I think it is

**Comment by bhajneet** [comment]
Yes, don't know which commit closed it
