### ISSUE TITLE
Missing Labels and Assignee for issue template

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/database-viewer#25]
If the user is not a contributor/owner of the repo there is no label or assignee applied.

**Comment by bhajneet** [comment]
https://developer.github.com/v3/issues/labels/#add-labels-to-an-issue

**Comment by saihaj** [comment]
I think this should be solved by the `.Github` repo. Still no need for this since the bot is applying label to these in DB

**Comment by bhajneet** [comment]
Correct, closing in favor of github automation solution
