### ISSUE TITLE
Scroll to top of page when going forward with page navigation

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/database-viewer#30]
If on mobile, one has to scroll back up to the top after every page turn.

**Comment by bhajneet** [comment]
The animation for scrolling to top of page after clicking "next page" is odd. It is loading the new page after scrolling up. It would be nicer to immediately delete/fade away the current page and insert the new page without any scroll change.

_Originally posted by @bhajneet in https://github.com/ShabadOS/database-viewer/pull/57#issuecomment-502707430_

**Comment by bhajneet** [comment]
Would like to see previous text fade out linearly in 125ms before new page is loaded.

**Comment by Harjot1Singh** [comment]
I put in 200ms, feel free to adjust down to 125 if it's too long
