### ISSUE TITLE
Use English translations from author

### ISSUE THREAD

**Issue by saihaj** [ShabadOS/database-viewer#307]
**Describe the bug**
If there are English translations available from author then use those instead of google translate.

**Screenshots**
![image](https://user-images.githubusercontent.com/44710980/92014869-89c97980-ed15-11ea-8113-cc1bcf09593e.png)

_Originally reported on [Slack](https://shabados.slack.com/archives/C8LH4UF5H/p1599066290001900)_

**Comment by Sarabveer** [comment]
Alongside this, it should be mentioned if its original (in the case of Bhai Manmohan Singh) or Google Translate.

**Comment by bhajneet** [comment]
The left side is for sources, the right side is for machine interpretation. If english is machine duplicated, not a big deal. Can open a new issue if it does become a problem, or can open a new issue to make the left and right side more descriptive in UI.
