### ISSUE TITLE
Clicking next line not working

### ISSUE THREAD

**Issue by saihaj** [ShabadOS/database-viewer#308]
**Describe the bug**
Clicking next line in Line Viewer for sources Ardaas and Zindagi Nama does nothing. 

**To Reproduce**
1. Go to 'https://database.shabados.com/sources/6/page/1/line/11/view'
2. Click on 'Right Arrow'
3. It will not go to next line

**Expected behavior**
It take you to next line.

**Screenshots**
React Dev Tools
![image](https://user-images.githubusercontent.com/44710980/92524136-3361ac80-f1e7-11ea-9767-d22231f6ff78.png)

**Comment by Harjot1Singh** [comment]
I think it's a bug to do with being on the last page, and will happen on the last page of any bani. Try it out and confirm.

**Comment by saihaj** [comment]
My bad I was using cypress and didn't really payed attention to the fact that it is a disabled button.
