### ISSUE TITLE
Template doesn't include link to line (`/line/XYZ`) for 'View'

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/database-viewer#66]
Template doesn't include link to line (`/line/XYZ`) for 'View'.

![image](https://user-images.githubusercontent.com/14130567/59612044-6a333a80-90ea-11e9-938d-2cf02def8b6f.png)

_Originally posted by @bhajneet in https://github.com/ShabadOS/database-viewer/pull/57#issuecomment-502706211_

**Comment by Harjot1Singh** [comment]
Would you prefer a redirect from that URL to the new one? Or can just modify it
