### ISSUE TITLE
Disable trackbar/next page for single page sources

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/database-viewer#69]
Ardaas has a single "page". The trackbar and "next page" buttons should not be purple, but instead should match the color of "previous page". The mouse cursor should also remain a pointer.

_Related PR https://github.com/ShabadOS/database-viewer/pull/57 and Issue https://github.com/ShabadOS/database-viewer/issues/68_

**Comment by Harjot1Singh** [comment]
Not sure I completely understand the action points here
